services:
  iam-service:
    build: .
    container_name: iam-service
    env_file:
      - docker.env
    ports:
      - "8080:8080"
    depends_on:
      - iam-db
      - redis
    networks:
      - iam-network

  iam-db:
    image: postgres:15-alpine
    container_name: iam-db
    environment:
      POSTGRES_DB: iam_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - iam-db-data:/var/lib/postgresql/data
    networks:
      - iam-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - iam-network

volumes:
  iam-db-data:

networks:
  iam-network: