server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        dialect: ${JPA_HIBERNATE_DIALECT}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  identity-provider:
    type: ${APP_IDENTITY_PROVIDER_TYPE:SELF}

  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8081}
    realm: ${KEYCLOAK_REALM:iam-realm}
    issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/iam-realm}
    user-client-id: ${KEYCLOAK_USER_CLIENT_ID:iam-user-client}
    user-client-secret: ${KEYCLOAK_USER_CLIENT_SECRET:}
    admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:iam-admin-client}
    admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
    redirect-uri: ${KEYCLOAK_REDIRECT_URI:http://localhost:3000/callback}

  domain-url: ${APP_DOMAIN_URL}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{correlationId}] %logger{36} - %msg%n"