name: Build Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build_executable_jar:
    runs-on: [self-hosted]

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v5

      - name: Cài đặt môi trường JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cấp quyền thực thi cho Maven Wrapper
        run: chmod +x ./mvnw

      - name: Biên dịch và đóng gói tệp JAR bằng Maven Wrapper
        run: ./mvnw clean package -DskipTests

      - name: Lưu trữ sản phẩm Artifact
        uses: actions/upload-artifact@v4
        with:
          name: user-service-jar
          path: target/*.jar
          retention-days: 3