name: Build User Service

on:
  push:
    branches:
      - main
    paths:
      - 'services/user-service/**'
      - 'services/common-lib/**'
      - '.github/workflows/ci.yml'

jobs:
  build_user_service:
    runs-on: [self-hosted]

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v5

      - name: Cài đặt JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build và install common-lib
        run: mvnw -f services/common-lib/pom.xml clean install -DskipTests

      - name: Build user-service
        run: mvnw -f services/user-service/pom.xml clean package -DskipTests

      - name: Lưu artifact user-service
        uses: actions/upload-artifact@v4
        with:
          name: user-service-jar
          path: services/user-service/target/*.jar
          retention-days: 3
