name: Build User Service

on:
  push:
    branches:
      - main
    paths:
      - 'services/user-service/**'
      - '.github/workflows/user-service-ci.yml'

jobs:
  build_user_service:
    runs-on: [self-hosted]

    defaults:
      run:
        working-directory: services/user-service

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v5

      - name: Cài đặt JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cấp quyền thực thi cho Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build User Service bằng Maven
        run: ./mvnw clean package -DskipTests

      - name: Lưu artifact
        uses: actions/upload-artifact@v4
        with:
          name: user-service-jar
          path: services/user-service/target/*.jar
          retention-days: 3